#!/bin/sh
# vim: set ft=sh sw=2 et :
#
# Additional inspiration:
# - https://gist.github.com/jmatsushita/5c50ef14b4b96cb24ae5268dab613050
# - https://github.com/LazyVim/LazyVim/discussions/1972
# - https://dev.jmgilman.com/environment/bootstrap/

install_brew() {
  # Proudly borrowed from:
  # https://github.com/duckfullstop/dotfiles/blob/f734eea399a7ccd1c25b57242997e79f230abc4d/.config/yadm/bootstrap

  # install Homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing Homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  fi
}

install_nix() {
  # This one courtesy of:
  # https://github.com/shadowrylander/shadowrylander/blob/35bb51822c46578d0a5da5810263fa85d464043c/.config/yadm/bootstrap#L56
  install_nix_bin() {
    curl -L https://nixos.org/nix/install | sh
    if [ -e '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh' ]; then
      # shellcheck source=/dev/null
      . '/nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh'
    fi
  }
  command -v nix >/dev/null 2>&1 || install_nix_bin

  system_type=$(uname -s)

  if [ "$system_type" = "Darwin" ]; then
    sudo xcodebuild -license accept
    nix run nix-darwin --experimental-feature nix-command --experimental-feature flakes -- switch --flake "$HOME}/.config/nix"
  fi
  nix run 'nixpkgs#home-manager' -- switch -b orig --flake "${HOME}/.config/nix"
  # TODO: Maybe use this: https://github.com/DeterminateSystems/nix-installer
  sudo -i nix-env --uninstall nix
}

configure_vim() {
  # Install vim-plug for Vim
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  vim +'PlugInstall --sync' +qa
  # FIXME: How to bootstrap LazyNvim?
  # # Install vim-plug for Neovim
  # sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
  #      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  # nvim +'PlugInstall --sync' +qa
}

install_brew
install_nix

configure_vim
